spring:
  application:
    name: raid-checker
  profiles:
    active: ${SPRING_PROFILE:dev}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        jdbc:
          time_zone: Asia/Seoul

server:
  port: ${PORT:8080}

# 로스트아크 API 설정
lostark:
  api:
    base-url: https://developer-lostark.game.onstove.com