spring:
  jackson:
    time-zone: Asia/Seoul
    serialization:
      write-dates-as-timestamps: false
  application:
    name: raid-checker
  profiles:
    active: ${SPRING_PROFILE:dev}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        jdbc:
          time_zone: Asia/Seoul  # ✅ 추가!

server:
  port: ${PORT:8080}
  timezone: Asia/Seoul  # ✅ 추가!
  servlet:
    session:
      cookie:
        same-site: lax
        http-only: true
        secure: false
      timeout: 30m

lostark:
  api:
    base-url: https://developer-lostark.game.onstove.com